name: Deploy Atomicask on push
on:
  push:
    branches:
      - prod
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.Env.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.env.SSH_PASSWORD }}
      SSH_PORT: ${{ secrets.Env.SSH_PORT }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd /var/www/vhosts/atomicask.com/httpdocs/
            git reset --hard
            git pull origin prod
            